/* empty css                      */(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))o(n);new MutationObserver(n=>{for(const s of n)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&o(f)}).observe(document,{childList:!0,subtree:!0});function r(n){const s={};return n.integrity&&(s.integrity=n.integrity),n.referrerPolicy&&(s.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?s.credentials="include":n.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(n){if(n.ep)return;n.ep=!0;const s=r(n);fetch(n.href,s)}})();const h="https://furniture-store.b.goit.study/api",l=document.querySelector(".categories-filter"),d=document.querySelector(".furniture-list"),u=document.querySelector(".load-more-btn");let i=[],c=[],a=null,g=8;async function L(){try{const e=await(await fetch(`${h}/categories`)).json();b(e)}catch(t){console.error("Помилка завантаження",t)}}function b(t){l.innerHTML="";const e=document.createElement("button");e.textContent="Всі товари",e.classList.add("active"),e.addEventListener("click",()=>p(null)),l.appendChild(e),t.forEach(r=>{const o=document.createElement("button");o.textContent=r.name,o.addEventListener("click",()=>p(r.name)),l.appendChild(o)})}function p(t){a=t,c=[],l.querySelectorAll("button").forEach(r=>{r.classList.remove("active"),r.textContent===(t||"Всі товари")&&r.classList.add("active")}),m()}async function v(){try{i=await(await fetch(`${h}/products`)).json(),m()}catch(t){console.error("Помилка завантаження товарів",t)}}function m(){d.innerHTML="",c=[];const t=a?i.filter(e=>e.category.name===a):i;if(t.length===0){d.innerHTML="Товарів не знайдено",u.style.display="none";return}u.style.display="block",y(t)}function y(t){const e=t.slice(c.length,c.length+g);c=c.concat(e),e.forEach(r=>{const o=document.createElement("li");o.classList.add("furniture-card"),o.innerHTML=`
            <img src="${r.image}" alt="${r.title}" />
            <div class="info">
                <h3 class="title">${r.title}</h3>
                <p class="price">${r.price} грн</p>
                <button class="details-btn" data-id="${r._id}">Детальніше</button>
            </div>
        `,d.appendChild(o)}),c.length>=t.length&&(u.style.display="none")}u.addEventListener("click",()=>{const t=a?i.filter(e=>e.category.name===a):i;y(t)});d.addEventListener("click",async t=>{if(t.target.classList.contains("details-btn")){const e=t.target.dataset.id;try{const o=await(await fetch(`${h}/products/${e}`)).json();showModal(o)}catch(r){console.error("Помилка завантаження деталей товару",r)}}});L();v();
//# sourceMappingURL=index.js.map
